@api = http://localhost:5001/fir-auth-d0f22/us-central1/api
@a = Bearer eyJhbGciOiJub25lIiwidHlwIjoiSldUIn0.eyJuYW1lIjoiUGVhY2ggUGVhY2giLCJyb2xlIjoiVGVhY2hlciIsImVtYWlsIjoicGVhY2gucGVhY2guNDdAdGVzdC5jb20iLCJlbWFpbF92ZXJpZmllZCI6dHJ1ZSwiYXV0aF90aW1lIjoxNjA2Nzg1NjY0LCJ1c2VyX2lkIjoiVzdvU1RuOUNpNTV1Q2hqeVJBUEpabVEwN3lSeiIsImZpcmViYXNlIjp7ImlkZW50aXRpZXMiOnsiZW1haWwiOlsicGVhY2gucGVhY2guNDdAdGVzdC5jb20iXSwiZ29vZ2xlLmNvbSI6WyIzMTUzNjE4ODgwNDc3NjY2NDUyMDA5NTkxMDMyODQzMTU3MjA0MjQ3Il19LCJzaWduX2luX3Byb3ZpZGVyIjoiZ29vZ2xlLmNvbSJ9LCJpYXQiOjE2MDY3ODU2NjQsImV4cCI6MTYwNjc4OTI2NCwiYXVkIjoiZmlyLWF1dGgtZDBmMjIiLCJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vZmlyLWF1dGgtZDBmMjIiLCJzdWIiOiJXN29TVG45Q2k1NXVDaGp5UkFQSlptUTA3eVJ6In0.

###
GET {{api}}/whrolly
Authorization: {{a}}

###
POST {{api}}/role/teacher
Authorization: {{a}}
###

POST {{api}}/role/student
Authorization: {{a}}
###

POST {{api}}/class
Authorization: {{a}}
Content-Type: application/json

{
    "name": "AP Calculus BC"
}

###
GET {{api}}/class
Authorization: {{a}}
Content-Type: application/json
