@api = http://localhost:5001/fir-auth-d0f22/us-central1/api
@a = Bearer eyJhbGciOiJub25lIiwidHlwIjoiSldUIn0.eyJuYW1lIjoiUGFuZGEgUGFuZGEiLCJyb2xlIjoiVGVhY2hlciIsImVtYWlsIjoicGFuZGEucGFuZGEuODU4QHRlc3QuY29tIiwiZW1haWxfdmVyaWZpZWQiOnRydWUsImF1dGhfdGltZSI6MTYwNjUyNDI0NCwidXNlcl9pZCI6InNaZWNibXJ1VWpSaVY4NHRhVGJCdHc2ZkZnR0EiLCJmaXJlYmFzZSI6eyJpZGVudGl0aWVzIjp7ImVtYWlsIjpbInBhbmRhLnBhbmRhLjg1OEB0ZXN0LmNvbSJdLCJnb29nbGUuY29tIjpbIjczNzcyNzM2ODQ2OTQyNzE4NzkyNDE5NjUzMTA4NjE4MzYyMjU0MDEiXX0sInNpZ25faW5fcHJvdmlkZXIiOiJnb29nbGUuY29tIn0sImlhdCI6MTYwNjUyNDI0NCwiZXhwIjoxNjA2NTI3ODQ0LCJhdWQiOiJmaXItYXV0aC1kMGYyMiIsImlzcyI6Imh0dHBzOi8vc2VjdXJldG9rZW4uZ29vZ2xlLmNvbS9maXItYXV0aC1kMGYyMiIsInN1YiI6InNaZWNibXJ1VWpSaVY4NHRhVGJCdHc2ZkZnR0EifQ.


###
GET {{api}}/whrolly
Authorization: {{a}}

###
POST {{api}}/role/teacher
Authorization: {{a}}
###

POST {{api}}/role/student
Authorization: {{a}}
###

POST {{api}}/class
Authorization: {{a}}
Content-Type: application/json

{
    "name": "Linear Algebra"
}

###
GET {{api}}/class
Authorization: {{a}}
Content-Type: application/json
