@api = http://localhost:5001/fir-auth-d0f22/us-central1/api
@a = Bearer eyJhbGciOiJub25lIiwidHlwIjoiSldUIn0.eyJuYW1lIjoiR3Jhc3MgT3JhbmdlIiwicm9sZSI6IlRlYWNoZXIiLCJlbWFpbCI6ImdyYXNzLm9yYW5nZS45NzFAdGVzdC5jb20iLCJlbWFpbF92ZXJpZmllZCI6dHJ1ZSwiYXV0aF90aW1lIjoxNjA2MjY0MjgwLCJ1c2VyX2lkIjoiSWVYVUVncWNLVDNZNldDQVVVZXQ1cmduV0VONyIsImZpcmViYXNlIjp7ImlkZW50aXRpZXMiOnsiZW1haWwiOlsiZ3Jhc3Mub3JhbmdlLjk3MUB0ZXN0LmNvbSJdLCJnb29nbGUuY29tIjpbIjYxMDAxMTM5ODg2NTM4MzA3MTE2MjY0MTQzNDUzMjMzMjcyMjEwNjIiXX0sInNpZ25faW5fcHJvdmlkZXIiOiJnb29nbGUuY29tIn0sImlhdCI6MTYwNjI2NDI4MCwiZXhwIjoxNjA2MjY3ODgwLCJhdWQiOiJmaXItYXV0aC1kMGYyMiIsImlzcyI6Imh0dHBzOi8vc2VjdXJldG9rZW4uZ29vZ2xlLmNvbS9maXItYXV0aC1kMGYyMiIsInN1YiI6IkllWFVFZ3FjS1QzWTZXQ0FVVWV0NXJnbldFTjcifQ.


###
GET {{api}}/whrolly
Authorization: {{a}}

###
POST {{api}}/role/teacher
Authorization: {{a}}
###

POST {{api}}/role/student
Authorization: {{a}}
###

POST {{api}}/class
Authorization: {{a}}
Content-Type: application/json

{
    "name": "Linear Algebra"
}

###
GET {{api}}/class
Authorization: {{a}}
Content-Type: application/json
